### ISSUE TITLE
求hua总交换友链

### ISSUE THREAD

**Issue by mu-yu** [tonghuashuo/tonghuashuo.github.io#2]
https://everain.me

厚颜无耻求友链…这两天刚开始搞…

**Comment by tonghuashuo** [comment]
Sure. Let me know when you're ready to go public. @mu-yu 
And about that UI... really ? (I've been working on an 2.0 upgrade anyway. So if you like the current style, feel free to use it. ha ha)

**Comment by mu-yu** [comment]
那个只是prototype…具体怎么做还没想好…而且最近不太有时间搞…而且不会设计样式只能想着去哪里抄抄了…囧…

**Comment by tonghuashuo** [comment]
@mu-yu 所以我说等你准备好对外开放了，我再放上去。UI 你要是喜欢随便拿去，反正我那也算不上什么原创，就随便搭了个架子，当初看还行，现在看适配有很大问题，外加我自己也审美疲劳了，打算换一套，连技术实现一起更新掉，正在做。

**Comment by mu-yu** [comment]
OK，等弄好跟你说… XD

**Comment by mu-yu** [comment]
基本成形了…可以愉快的发post了…虽然目前还是丑丑的，但是勉强可以对外啦…
不过还有很多微小的工作要做…

**Comment by tonghuashuo** [comment]
@mu-yu OK收到

**Comment by tonghuashuo** [comment]
@mu-yu 已添加
